language: node_js
sudo: false
node_js:
  - "6"
services:
  - mongodb
before_script: "npm run init"
script: "npm run test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
