version: '2'
services:
  mongo:
    image: mongo:3.2
    restart: always
  octon:
    build:
      context: ../../
      dockerfile: Dockerfile
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/octon
    ports:
      - "3000:3000"
    restart: always
